GalleryBundle\Entity\User:
    type: entity
    table: User
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        firstname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        surname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        dob:
            type: datetime
            nullable: false
            comment: ''
        created:
            type: datetime
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
